// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tecnicell.Server.Context;

#nullable disable

namespace Tecnicell.Server.Migrations
{
    [DbContext(typeof(TecnicellContext))]
    [Migration("20241111153026_DiaryWorkFixed")]
    partial class DiaryWorkFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Accessory", b =>
                {
                    b.Property<string>("AccessoryCode")
                        .HasColumnType("character varying")
                        .HasColumnName("accessory_code");

                    b.Property<string>("AccessoryType")
                        .HasColumnType("character varying")
                        .HasColumnName("accessory_type");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.HasKey("AccessoryCode")
                        .HasName("accessory_pkey");

                    b.HasIndex("AccessoryType");

                    b.HasIndex("ImageCode");

                    b.ToTable("accessory", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.AccessoryHistory", b =>
                {
                    b.Property<string>("AccessoryCode")
                        .HasColumnType("character varying")
                        .HasColumnName("accessory_code");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("ActionHistory")
                        .HasColumnType("character varying")
                        .HasColumnName("action_history");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("character varying")
                        .HasColumnName("supplier_code");

                    b.Property<string>("ToBranch")
                        .HasColumnType("character varying")
                        .HasColumnName("to_branch");

                    b.HasKey("AccessoryCode", "Date", "UserCode")
                        .HasName("accessory_history_pkey");

                    b.HasIndex("ActionHistory");

                    b.HasIndex("SaleCode");

                    b.HasIndex("SupplierCode");

                    b.HasIndex("ToBranch");

                    b.HasIndex("UserCode");

                    b.ToTable("accessory_history", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.AccessoryType", b =>
                {
                    b.Property<string>("AccessoryTypeCode")
                        .HasColumnType("character varying")
                        .HasColumnName("accessory_type_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("AccessoryTypeCode")
                        .HasName("accessory_type_pkey");

                    b.ToTable("accessory_type", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.AccessoryView", b =>
                {
                    b.Property<string>("Available")
                        .HasColumnType("TEXT")
                        .HasColumnName("available");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<long?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.Property<string>("TypeCode")
                        .HasColumnType("character varying")
                        .HasColumnName("type_code");

                    b.ToTable((string)null);

                    b.ToView("accessory_view", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.ActionHistory", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("action_history_pkey");

                    b.ToTable("action_history", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Battery", b =>
                {
                    b.Property<string>("BatteryCode")
                        .HasColumnType("character varying")
                        .HasColumnName("battery_code");

                    b.Property<string>("Brand")
                        .HasColumnType("character varying")
                        .HasColumnName("brand");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.Property<int?>("Warranty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warranty");

                    b.HasKey("BatteryCode")
                        .HasName("battery_pkey");

                    b.HasIndex("Brand");

                    b.HasIndex("ImageCode");

                    b.ToTable("battery", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.BatteryHistory", b =>
                {
                    b.Property<string>("BatteryCode")
                        .HasColumnType("character varying")
                        .HasColumnName("battery_code");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("ActionHistory")
                        .HasColumnType("character varying")
                        .HasColumnName("action_history");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("character varying")
                        .HasColumnName("supplier_code");

                    b.Property<string>("ToBranch")
                        .HasColumnType("character varying")
                        .HasColumnName("to_branch");

                    b.HasKey("BatteryCode", "Date", "UserCode")
                        .HasName("battery_history_pkey");

                    b.HasIndex("ActionHistory");

                    b.HasIndex("SaleCode");

                    b.HasIndex("SupplierCode");

                    b.HasIndex("ToBranch");

                    b.HasIndex("UserCode");

                    b.ToTable("battery_history", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.BatteryView", b =>
                {
                    b.Property<string>("Available")
                        .HasColumnType("TEXT")
                        .HasColumnName("available");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<long?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.Property<int?>("Warranty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warranty");

                    b.ToTable((string)null);

                    b.ToView("battery_view", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Branch", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasColumnType("character varying")
                        .HasColumnName("branch_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("BranchCode")
                        .HasName("branch_pkey");

                    b.ToTable("branch", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Brand", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.HasKey("Name")
                        .HasName("brand_pkey");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasColumnType("character varying")
                        .HasColumnName("currency_code");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("character varying")
                        .HasColumnName("currency_name");

                    b.HasKey("CurrencyCode")
                        .HasName("currency_pkey");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.DiaryWork", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Date");

                    b.HasIndex("SaleCode");

                    b.HasIndex("UserCode");

                    b.HasIndex("WorkType");

                    b.ToTable("diary_work", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Image", b =>
                {
                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<byte[]>("File")
                        .HasColumnType("BLOB")
                        .HasColumnName("file");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("ImageCode")
                        .HasName("image_pkey");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Phone", b =>
                {
                    b.Property<string>("Imei")
                        .HasColumnType("character varying")
                        .HasColumnName("imei");

                    b.Property<string>("Brand")
                        .HasColumnType("character varying")
                        .HasColumnName("brand");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.HasKey("Imei")
                        .HasName("phone_pkey");

                    b.HasIndex("Brand");

                    b.HasIndex("ImageCode");

                    b.ToTable("phone", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneHistory", b =>
                {
                    b.Property<string>("Imei")
                        .HasColumnType("character varying")
                        .HasColumnName("imei");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("ActionHistory")
                        .HasColumnType("character varying")
                        .HasColumnName("action_history");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("character varying")
                        .HasColumnName("supplier_code");

                    b.Property<string>("ToBranch")
                        .HasColumnType("character varying")
                        .HasColumnName("to_branch");

                    b.HasKey("Imei", "Date", "UserCode")
                        .HasName("phone_history_pkey");

                    b.HasIndex("ActionHistory");

                    b.HasIndex("SaleCode");

                    b.HasIndex("SupplierCode");

                    b.HasIndex("ToBranch");

                    b.HasIndex("UserCode");

                    b.ToTable("phone_history", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneRepair", b =>
                {
                    b.Property<string>("Imei")
                        .HasColumnType("character varying")
                        .HasColumnName("imei");

                    b.Property<string>("Brand")
                        .HasColumnType("character varying")
                        .HasColumnName("brand");

                    b.Property<string>("CustomerId")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_number");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.HasKey("Imei")
                        .HasName("phone_repair_pkey");

                    b.HasIndex("Brand");

                    b.HasIndex("ImageCode");

                    b.ToTable("phone_repair", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneRepairHistory", b =>
                {
                    b.Property<string>("Imei")
                        .HasColumnType("character varying")
                        .HasColumnName("imei");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("ActionHistory")
                        .HasColumnType("character varying")
                        .HasColumnName("action_history");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<string>("ToBranch")
                        .HasColumnType("character varying")
                        .HasColumnName("to_branch");

                    b.HasKey("Imei", "Date", "UserCode")
                        .HasName("phone_repair_history_pkey");

                    b.HasIndex("ActionHistory");

                    b.HasIndex("SaleCode");

                    b.HasIndex("ToBranch");

                    b.HasIndex("UserCode");

                    b.ToTable("phone_repair_history", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneRepairView", b =>
                {
                    b.Property<string>("ActionDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("action_description");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<string>("CurrentState")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_state");

                    b.Property<string>("CustomerId")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("character varying")
                        .HasColumnName("customer_number");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.ToTable((string)null);

                    b.ToView("phone_repair_view", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneView", b =>
                {
                    b.Property<string>("ActionDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("action_description");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost");

                    b.Property<string>("CurrentState")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_state");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.ToTable((string)null);

                    b.ToView("phone_view", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Role", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("role_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("RoleCode")
                        .HasName("role_pkey");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Sale", b =>
                {
                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT")
                        .HasColumnName("cost");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("character varying")
                        .HasColumnName("currency_code");

                    b.Property<DateTime?>("Warranty")
                        .HasColumnType("TEXT")
                        .HasColumnName("warranty");

                    b.HasKey("SaleCode")
                        .HasName("sale_pkey");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("sale", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Screen", b =>
                {
                    b.Property<string>("ScreenCode")
                        .HasColumnType("character varying")
                        .HasColumnName("screen_code");

                    b.Property<string>("Brand")
                        .HasColumnType("character varying")
                        .HasColumnName("brand");

                    b.Property<decimal?>("Height")
                        .HasColumnType("TEXT")
                        .HasColumnName("height");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.Property<int?>("Warranty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warranty");

                    b.Property<decimal?>("Width")
                        .HasColumnType("TEXT")
                        .HasColumnName("width");

                    b.HasKey("ScreenCode")
                        .HasName("screen_pkey");

                    b.HasIndex("Brand");

                    b.HasIndex("ImageCode");

                    b.ToTable("screen", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.ScreenHistory", b =>
                {
                    b.Property<string>("ScreenCode")
                        .HasColumnType("character varying")
                        .HasColumnName("screen_code");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("ActionHistory")
                        .HasColumnType("character varying")
                        .HasColumnName("action_history");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("SaleCode")
                        .HasColumnType("character varying")
                        .HasColumnName("sale_code");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("character varying")
                        .HasColumnName("supplier_code");

                    b.Property<string>("ToBranch")
                        .HasColumnType("character varying")
                        .HasColumnName("to_branch");

                    b.HasKey("ScreenCode", "Date", "UserCode")
                        .HasName("screen_history_pkey");

                    b.HasIndex("ActionHistory");

                    b.HasIndex("SaleCode");

                    b.HasIndex("SupplierCode");

                    b.HasIndex("ToBranch");

                    b.HasIndex("UserCode");

                    b.ToTable("screen_history", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.ScreenView", b =>
                {
                    b.Property<string>("Available")
                        .HasColumnType("TEXT")
                        .HasColumnName("available");

                    b.Property<string>("Code")
                        .HasColumnType("character varying")
                        .HasColumnName("code");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<long?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("sale_price");

                    b.Property<string>("Type")
                        .HasColumnType("character varying")
                        .HasColumnName("type");

                    b.Property<int?>("Warranty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("warranty");

                    b.ToTable((string)null);

                    b.ToView("screen_view", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Search", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Value")
                        .HasColumnType("character varying")
                        .HasColumnName("value");

                    b.HasKey("Date")
                        .HasName("searchs_pkey");

                    b.ToTable("searchs", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Supplier", b =>
                {
                    b.Property<string>("SupplierCode")
                        .HasColumnType("character varying")
                        .HasColumnName("supplier_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("SupplierCode");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Usd", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.HasKey("Date")
                        .HasName("usd_pkey");

                    b.ToTable("usd", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.UserAccount", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.HasKey("UserCode")
                        .HasName("user_account_pkey");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.UserInfo", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("character varying")
                        .HasColumnName("user_code");

                    b.Property<string>("Branch")
                        .HasColumnType("character varying")
                        .HasColumnName("branch");

                    b.Property<string>("ImageCode")
                        .HasColumnType("character varying")
                        .HasColumnName("image_code");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("character varying")
                        .HasColumnName("role");

                    b.HasKey("UserCode")
                        .HasName("user_info_pkey");

                    b.HasIndex("Branch");

                    b.HasIndex("ImageCode");

                    b.HasIndex("Role");

                    b.ToTable("user_info", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.WorkType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("accessory_code");

                    b.HasKey("Name");

                    b.ToTable("work_type", (string)null);
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Accessory", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.AccessoryType", "AccessoryTypeNavigation")
                        .WithMany("Accessories")
                        .HasForeignKey("AccessoryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("accessory_accessory_type_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Image", "ImageCodeNavigation")
                        .WithMany("Accessories")
                        .HasForeignKey("ImageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("accessory_image_code_fkey");

                    b.Navigation("AccessoryTypeNavigation");

                    b.Navigation("ImageCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.AccessoryHistory", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Accessory", "AccessoryCodeNavigation")
                        .WithMany("AccessoryHistories")
                        .HasForeignKey("AccessoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("accessory_history_accessory_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.ActionHistory", "ActionHistoryNavigation")
                        .WithMany("AccessoryHistories")
                        .HasForeignKey("ActionHistory")
                        .HasConstraintName("accessory_history_action_history_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Sale", "SaleCodeNavigation")
                        .WithMany("AccessoryHistories")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("accessory_history_sale_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Supplier", "SupplierNavigation")
                        .WithMany("AccessoryHistories")
                        .HasForeignKey("SupplierCode")
                        .HasConstraintName("accessory_history_supplier_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Branch", "ToBranchNavigation")
                        .WithMany("AccessoryHistories")
                        .HasForeignKey("ToBranch")
                        .HasConstraintName("accessory_history_to_branch_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithMany("AccessoryHistories")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("accessory_history_user_code_fkey");

                    b.Navigation("AccessoryCodeNavigation");

                    b.Navigation("ActionHistoryNavigation");

                    b.Navigation("SaleCodeNavigation");

                    b.Navigation("SupplierNavigation");

                    b.Navigation("ToBranchNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Battery", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Brand", "BrandNavigation")
                        .WithMany("Batteries")
                        .HasForeignKey("Brand")
                        .HasConstraintName("battery_brand_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Image", "ImageCodeNavigation")
                        .WithMany("Batteries")
                        .HasForeignKey("ImageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("battery_image_code_fkey");

                    b.Navigation("BrandNavigation");

                    b.Navigation("ImageCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.BatteryHistory", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.ActionHistory", "ActionHistoryNavigation")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("ActionHistory")
                        .HasConstraintName("battery_history_action_history_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Battery", "BatteryCodeNavigation")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("BatteryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("battery_history_battery_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Sale", "SaleCodeNavigation")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("battery_history_sale_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Supplier", "SupplierNavigation")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("SupplierCode")
                        .HasConstraintName("battery_history_supplier_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Branch", "ToBranchNavigation")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("ToBranch")
                        .HasConstraintName("battery_history_to_branch_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithMany("BatteryHistories")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("battery_history_user_code_fkey");

                    b.Navigation("ActionHistoryNavigation");

                    b.Navigation("BatteryCodeNavigation");

                    b.Navigation("SaleCodeNavigation");

                    b.Navigation("SupplierNavigation");

                    b.Navigation("ToBranchNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.DiaryWork", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Sale", "SaleCodeNavigation")
                        .WithMany("DiaryWorks")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("dairy_work_sale_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithMany("DiaryWorks")
                        .HasForeignKey("UserCode")
                        .HasConstraintName("dairy_work_user_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.WorkType", "WorkTypeNavigation")
                        .WithMany("DiaryWorks")
                        .HasForeignKey("WorkType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Dairy_Work_Work_Type");

                    b.Navigation("SaleCodeNavigation");

                    b.Navigation("UserCodeNavigation");

                    b.Navigation("WorkTypeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Phone", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Brand", "BrandNavigation")
                        .WithMany("Phones")
                        .HasForeignKey("Brand")
                        .HasConstraintName("phone_brand_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Image", "ImageCodeNavigation")
                        .WithMany("Phones")
                        .HasForeignKey("ImageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("phone_image_code_fkey");

                    b.Navigation("BrandNavigation");

                    b.Navigation("ImageCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneHistory", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.ActionHistory", "ActionHistoryNavigation")
                        .WithMany("PhoneHistories")
                        .HasForeignKey("ActionHistory")
                        .HasConstraintName("phone_history_action_history_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Phone", "ImeiNavigation")
                        .WithMany("PhoneHistories")
                        .HasForeignKey("Imei")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("phone_history_imei_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Sale", "SaleCodeNavigation")
                        .WithMany("PhoneHistories")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("phone_history_sale_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Supplier", "SupplierNavigation")
                        .WithMany("PhoneHistories")
                        .HasForeignKey("SupplierCode")
                        .HasConstraintName("phone_history_supplier_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Branch", "ToBranchNavigation")
                        .WithMany("PhoneHistories")
                        .HasForeignKey("ToBranch")
                        .HasConstraintName("phone_history_to_branch_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithMany("PhoneHistories")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("phone_history_user_code_fkey");

                    b.Navigation("ActionHistoryNavigation");

                    b.Navigation("ImeiNavigation");

                    b.Navigation("SaleCodeNavigation");

                    b.Navigation("SupplierNavigation");

                    b.Navigation("ToBranchNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneRepair", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Brand", "BrandNavigation")
                        .WithMany("PhoneRepairs")
                        .HasForeignKey("Brand")
                        .HasConstraintName("phone_repair_brand_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Image", "ImageCodeNavigation")
                        .WithMany("PhoneRepairs")
                        .HasForeignKey("ImageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("phone_repair_image_code_fkey");

                    b.Navigation("BrandNavigation");

                    b.Navigation("ImageCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneRepairHistory", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.ActionHistory", "ActionHistoryNavigation")
                        .WithMany("PhoneRepairHistories")
                        .HasForeignKey("ActionHistory")
                        .HasConstraintName("phone_repair_history_action_history_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.PhoneRepair", "ImeiNavigation")
                        .WithMany("PhoneRepairHistories")
                        .HasForeignKey("Imei")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("phone_repair_history_imei_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Sale", "SaleCodeNavigation")
                        .WithMany("PhoneRepairHistories")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("phone_repair_history_sale_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Branch", "ToBranchNavigation")
                        .WithMany("PhoneRepairHistories")
                        .HasForeignKey("ToBranch")
                        .HasConstraintName("phone_repair_history_to_branch_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithMany("PhoneRepairHistories")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("phone_repair_history_user_code_fkey");

                    b.Navigation("ActionHistoryNavigation");

                    b.Navigation("ImeiNavigation");

                    b.Navigation("SaleCodeNavigation");

                    b.Navigation("ToBranchNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Sale", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Currency", "CurrencyCodeNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("CurrencyCode")
                        .HasConstraintName("sale_currency_code_fkey");

                    b.Navigation("CurrencyCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Screen", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Brand", "BrandNavigation")
                        .WithMany("Screens")
                        .HasForeignKey("Brand")
                        .HasConstraintName("screen_brand_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Image", "ImageCodeNavigation")
                        .WithMany("Screens")
                        .HasForeignKey("ImageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("screen_image_code_fkey");

                    b.Navigation("BrandNavigation");

                    b.Navigation("ImageCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.ScreenHistory", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.ActionHistory", "ActionHistoryNavigation")
                        .WithMany("ScreenHistories")
                        .HasForeignKey("ActionHistory")
                        .HasConstraintName("screen_history_action_history_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Sale", "SaleCodeNavigation")
                        .WithMany("ScreenHistories")
                        .HasForeignKey("SaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("screen_history_sale_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Screen", "ScreenCodeNavigation")
                        .WithMany("ScreenHistories")
                        .HasForeignKey("ScreenCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("screen_history_screen_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Supplier", "SupplierNavigation")
                        .WithMany("ScreenHistories")
                        .HasForeignKey("SupplierCode")
                        .HasConstraintName("screen_history_supplier_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Branch", "ToBranchNavigation")
                        .WithMany("ScreenHistories")
                        .HasForeignKey("ToBranch")
                        .HasConstraintName("screen_history_to_branch_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithMany("ScreenHistories")
                        .HasForeignKey("UserCode")
                        .IsRequired()
                        .HasConstraintName("screen_history_user_code_fkey");

                    b.Navigation("ActionHistoryNavigation");

                    b.Navigation("SaleCodeNavigation");

                    b.Navigation("ScreenCodeNavigation");

                    b.Navigation("SupplierNavigation");

                    b.Navigation("ToBranchNavigation");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.UserAccount", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.UserInfo", "UserCodeNavigation")
                        .WithOne("UserAccount")
                        .HasForeignKey("Tecnicell.Server.Models.Entity.UserAccount", "UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_account_user_code_fkey");

                    b.Navigation("UserCodeNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.UserInfo", b =>
                {
                    b.HasOne("Tecnicell.Server.Models.Entity.Branch", "BranchNavigation")
                        .WithMany("UserInfos")
                        .HasForeignKey("Branch")
                        .HasConstraintName("user_info_branch_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Image", "ImageCodeNavigation")
                        .WithMany("UserInfos")
                        .HasForeignKey("ImageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("user_info_image_code_fkey");

                    b.HasOne("Tecnicell.Server.Models.Entity.Role", "RoleNavigation")
                        .WithMany("UserInfos")
                        .HasForeignKey("Role")
                        .HasConstraintName("user_info_role_fkey");

                    b.Navigation("BranchNavigation");

                    b.Navigation("ImageCodeNavigation");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Accessory", b =>
                {
                    b.Navigation("AccessoryHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.AccessoryType", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.ActionHistory", b =>
                {
                    b.Navigation("AccessoryHistories");

                    b.Navigation("BatteryHistories");

                    b.Navigation("PhoneHistories");

                    b.Navigation("PhoneRepairHistories");

                    b.Navigation("ScreenHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Battery", b =>
                {
                    b.Navigation("BatteryHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Branch", b =>
                {
                    b.Navigation("AccessoryHistories");

                    b.Navigation("BatteryHistories");

                    b.Navigation("PhoneHistories");

                    b.Navigation("PhoneRepairHistories");

                    b.Navigation("ScreenHistories");

                    b.Navigation("UserInfos");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Brand", b =>
                {
                    b.Navigation("Batteries");

                    b.Navigation("PhoneRepairs");

                    b.Navigation("Phones");

                    b.Navigation("Screens");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Currency", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Image", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Batteries");

                    b.Navigation("PhoneRepairs");

                    b.Navigation("Phones");

                    b.Navigation("Screens");

                    b.Navigation("UserInfos");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Phone", b =>
                {
                    b.Navigation("PhoneHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.PhoneRepair", b =>
                {
                    b.Navigation("PhoneRepairHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Role", b =>
                {
                    b.Navigation("UserInfos");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Sale", b =>
                {
                    b.Navigation("AccessoryHistories");

                    b.Navigation("BatteryHistories");

                    b.Navigation("DiaryWorks");

                    b.Navigation("PhoneHistories");

                    b.Navigation("PhoneRepairHistories");

                    b.Navigation("ScreenHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Screen", b =>
                {
                    b.Navigation("ScreenHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.Supplier", b =>
                {
                    b.Navigation("AccessoryHistories");

                    b.Navigation("BatteryHistories");

                    b.Navigation("PhoneHistories");

                    b.Navigation("ScreenHistories");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.UserInfo", b =>
                {
                    b.Navigation("AccessoryHistories");

                    b.Navigation("BatteryHistories");

                    b.Navigation("DiaryWorks");

                    b.Navigation("PhoneHistories");

                    b.Navigation("PhoneRepairHistories");

                    b.Navigation("ScreenHistories");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Tecnicell.Server.Models.Entity.WorkType", b =>
                {
                    b.Navigation("DiaryWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
